# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dcc3b50ecf66648085cb43c886046113b455e9aaae6bc670ffac5edd5ef6d833c19920b8bf3b7c707e027771b26d23718460c4f1d59d6c0e8d033ecf87613f6

test:
  secret_key_base: 97e49765aecc9c39fbbaa344a9df160bc6b725176a0f7d06fe4766f8527fb92a82f81a137e288423d001dfd184c52ffd5fc9a7dcb56dac9b7d32d814beef53ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
